# Generated by Django 2.2.4 on 2019-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('source', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('video', models.CharField(max_length=200)),
            ],
        ),
    ]
